pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                maven('java-tomcat-sample/pom.xml','clean package')
            }
            post {
                success {
                    print "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        
    }
 }
